DELETE http://localhost:3003/api/blogs/64610ed0a502cb0a6f39330b HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjhtYW4yMDAyIiwiaWQiOiI2NDYwZjg1OGJkNjU2NjA3ODFkMjE3YjQiLCJpYXQiOjE2ODQwODEzMDF9.jz3XxSBajotBI2VI8if_1mAOEfCS78eQHItEw59iAkY